

export const ADD_USER = "ADD_USER";
export const ADD_USER_LOADING = 'ADD_USER_LOADING';
export const ADD_USER_FAILED = "ADD_USER_FAILED";


export const GET_USER = "GET_USER";
export const GET_USER_LOADING = 'GET_USER_LOADING';
export const GET_USER_FAILED = "GET_USER_FAILED";


export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_LOADING = 'UPDATE_USER_LOADING';
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";



export const GET_MAIN_POSTER = "GET_MAIN_POSTER";
export const GET_MAIN_POSTER_LOADING = 'GET_MAIN_POSTER_LOADING';
export const GET_MAIN_POSTER_FAILED = "GET_MAIN_POSTER_FAILED";


export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_LOADING = 'GET_CATEGORIES_LOADING';
export const GET_CATEGORIES_FAILED = "GET_CATEGORIES_FAILED";


export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_LOADING = 'GET_PRODUCTS_LOADING';
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";


export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_LOADING = 'GET_PRODUCT_LOADING';
export const GET_PRODUCT_FAILED = "GET_PRODUCT_FAILED";


export const BUY_PRODUCT = "BUY_PRODUCT";
export const BUY_PRODUCT_LOADING = 'BUY_PRODUCT_LOADING';
export const BUY_PRODUCT_FAILED = "BUY_PRODUCT_FAILED";


export const RATE_PRODUCT = "RATE_PRODUCT";
export const RATE_PRODUCT_LOADING = 'RATE_PRODUCT_LOADING';
export const RATE_PRODUCT_FAILED = "RATE_PRODUCT_FAILED";


export const CANCEL_PRODUCT = "CANCEL_PRODUCT";
export const CANCEL_PRODUCT_LOADING = 'CANCEL_PRODUCT_LOADING';
export const CANCEL_PRODUCT_FAILED = "CANCEL_PRODUCT_FAILED";


export const GET_CANCEL_PRODUCTS = "GET_CANCEL_PRODUCTS";
export const GET_CANCEL_PRODUCTS_LOADING = 'GET_CANCEL_PRODUCTS_LOADING';
export const GET_CANCEL_PRODUCTS_FAILED = "GET_CANCEL_PRODUCTS_FAILED";


export const CART_PRODUCT = "CART_PRODUCT";
export const CART_PRODUCT_LOADING = 'CART_PRODUCT_LOADING';
export const CART_PRODUCT_FAILED = "CART_PRODUCT_FAILED";


export const GET_CART = "GET_CART";
export const GET_CART_LOADING = 'GET_CART_LOADING';
export const GET_CART_FAILED = "GET_CART_FAILED";


export const REMOVE_CART_PRODUCT = "REMOVE_CART_PRODUCT";
export const REMOVE_CART_PRODUCT_LOADING = 'REMOVE_CART_PRODUCT_LOADING';
export const REMOVE_CART_PRODUCT_FAILED = "REMOVE_CART_PRODUCT_FAILED";


export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDERS_LOADING = 'GET_ORDERS_LOADING';
export const GET_ORDERS_FAILED = "GET_ORDERS_FAILED";


export const GET_ORDER = "GET_ORDER";
export const GET_ORDER_LOADING = 'GET_ORDER_LOADING';
export const GET_ORDER_FAILED = "GET_ORDER_FAILED";


export const GET_KEYWORDS = "GET_KEYWORDS";
export const GET_KEYWORDS_LOADING = 'GET_KEYWORDS_LOADING';
export const GET_KEYWORDS_FAILED = "GET_KEYWORDS_FAILED";